Features/delete web api++
cis-cs-capstone-course/TAG pull request #18
Opened 2019-10-31 20:20 UTC by tmarkn

merge the right click to delete (annotations, documents, and labels)
added adding multiple files at once (also checks if it is a txt file)
added machine learning annotate button (spits it out to the console currently)
created json add function (also works for importing json from mlalgorithm)
added sending to algorithm
fixed rename bug

2019-10-31 23:04 UTC, ghost requested changes
veddy nice, just small changes

2019-10-31 23:04 UTC, ghost commented on static/js/classes/tagmodel.js
> +    console.log("Relabeled annotation to " + newName + ".");
Relabeled which annotation?

2019-10-31 23:04 UTC, ghost commented on static/js/classes/tagmodel.js
> +    this.currentDoc = this.openDocs[0];
Needs exception handling for a possible empty array

2019-10-31 23:04 UTC, ghost commented on static/js/classes/tagmodel.js
> +    let content = this.currentDoc.text.substring(range.startPosition, range.endPosition);
Any reason the trim was removed? Every double-clicked highlight is appended with a space otherwise

2019-10-31 23:04 UTC, NicoG96 commented on static/js/app.js
> +  console.log('Annotation Deleted');
Which annotation?

2019-11-01 00:12 UTC, tmarkn commented on static/js/classes/tagmodel.js
> +    let content = this.currentDoc.text.substring(range.startPosition, range.endPosition);
Yes, we should be removing the trailing whitespace, however the range start and end positions should also reflect the change as well.
Not going to update it at this moment, but this more accurately reflects the start and end positions.

2019-11-01 00:17 UTC, tmarkn commented on static/js/classes/tagmodel.js
> +    this.currentDoc = this.openDocs[0];
Not needed, opendocs will be just be set to itself.

2019-11-01 00:27 UTC, tmarkn commented on static/js/app.js
> +  console.log('Annotation Deleted');
Removed: was redundant

2019-11-01 00:28 UTC, tmarkn commented on static/js/classes/tagmodel.js
> +    console.log("Relabeled annotation to " + newName + ".");
Updated

2019-11-01 01:49 UTC, ghost submitted a review, later dismissed

2019-11-01 18:38 UTC, ghost approved these changes

2019-11-03 01:43 UTC, keithudock approved these changes

2019-11-03 01:49 UTC, merged