Bugfix/overlaps
cis-cs-capstone-course/TAG pull request #33
Opened 2019-11-08 01:40 UTC by tmarkn

- Created our own highlight functionality (fixed overlaps not rendering)
- Purged the highlight node module.
- Added default highlight functionality creates a dropdown for highlight  and delete
- - Hold 'a' to quick add
- - Hold 'd' to quick delete
- Added sorted push functionality for highlights
- Added substring deletion
- Added different heights per category

2019-11-08 01:58 UTC, ghost requested changes
Got damn mf Ray Charles with the keyboard my god. Just 1 minor thing:

Edit: It might be worthwhile to only prompt with the 'which' panel when a highlight already exists. Then its behavior could just default to highlight. Just a suggestion

2019-11-08 01:58 UTC, NicoG96 commented on static/js/classes/tagmodel.js
> +    console.log("Removing part of annotation: " + this.currentDoc.text.substring(range.startPosition, range.endPosition));
This prints every time, even if the delete is invalid.

2019-11-08 22:12 UTC, ghost approved these changes

2019-11-09 03:05 UTC, tuj52136 approved these changes

2019-11-09 03:08 UTC, merged